init project

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -47,8 +47,6 @@ jobs:
         repo: pulumi/pulumictl
     - name: Set PreRelease Version
       run: echo "GORELEASER_CURRENT_TAG=v$(pulumictl get version --language generic)" >> $GITHUB_ENV
-    - name : debug ls
-      run: ls -al ./provider/cmd/pulumi-resource-kind/
     - name: Run GoReleaser
       uses: goreleaser/goreleaser-action@v2
       with:
@@ -64,12 +62,62 @@ jobs:
     runs-on: ubuntu-latest
     needs: publish_binary
     steps:
-    - name: Publish SDKs
-      uses: pulumi/pulumi-package-publisher@v0.0.6
+      - name: Checkout Repo
+        uses: actions/checkout@v2
+      - name: Unshallow clone for tags
+        run: git fetch --prune --unshallow --tags
+      - name: Install Go
+        uses: actions/setup-go@v2
+        with:
+          go-version: ${{ matrix.goversion }}
+      - name: Install pulumictl
+        uses: jaxxstorm/action-install-gh-release@v1.5.0
+        with:
+          repo: pulumi/pulumictl
+      - name: Install Pulumi CLI
+        uses: pulumi/action-install-pulumi-cli@v2.0.0
+      - name: Setup Node
+        uses: actions/setup-node@v1
+        with:
+          node-version: ${{matrix.nodeversion}}
+          registry-url: ${{env.NPM_REGISTRY_URL}}
+      - name: Build SDK
+        run: make build_${{ matrix.language }}
+      - name: Check worktree clean
+        run: |
+          git update-index -q --refresh
+          if ! git diff-files --quiet; then
+              >&2 echo "error: working tree is not clean, aborting!"
+              git status
+              git diff
+              exit 1
+          fi
+      - if: ${{ matrix.language == 'nodejs' && env.PUBLISH_NPM == 'true' }}
+        uses: JS-DevTools/npm-publish@v1
+        with:
+          access: "public"
+          token: ${{ env.NPM_TOKEN }}
+          package: ${{github.workspace}}/sdk/nodejs/bin/package.json
     strategy:
       fail-fast: true
       matrix:
+        goversion:
+          - 1.19.x
         language:
           - nodejs
         nodeversion:
           - 18.x
+   #publish_sdk:
+   #  name: Publish SDKs
+   #  runs-on: ubuntu-latest
+   #  needs: publish_binary
+   #  steps:
+   #  - name: Publish SDKs
+   #    uses: pulumi/pulumi-package-publisher@v0.0.6
+   #  strategy:
+   #    fail-fast: true
+   #    matrix:
+   #      language:
+   #        - nodejs
+   #      nodeversion:
+   #        - 18.x
